import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ folder structure, so a new Markdown
 * file appears in the nav without editing this file. Control ordering with the
 * `sidebar_position` frontmatter field, and category labels with the
 * `_category_.json` file inside each subfolder.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
